# Generated by Django 2.0.2 on 2018-04-05 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180405_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 18, 58, 19, 869427, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
